### ISSUE TITLE
Doesn't find the DNS server

### ISSUE THREAD

**Issue by DLewis01** [serain/mailspoof#7]
Traceback (most recent call last):
  File "./mailspoof", line 10, in <module>
    sys.exit(main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mailspoof/__init__.py", line 42, in main
    'issues': spoof_check(domain)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mailspoof/scanners.py", line 249, in __call__
    return self.spf_check(domain) + self.dmarc_check(domain)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mailspoof/scanners.py", line 40, in __call__
    spf_record = self.fetch(domain)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mailspoof/scanners.py", line 225, in __call__
    txt_records = self.resolver.query(domain, 'TXT')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dns/resolver.py", line 1041, in query
    timeout = self._compute_timeout(start)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dns/resolver.py", line 858, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 5.004148006439209 seconds

**Comment by serain** [comment]
Hi @DLewis01 ,

Can you please give a full example, include input?

**Comment by DLewis01** [comment]
./mailspoof -d github.com -d reddit.com -iL /tmp/list
Traceback (most recent call last):
  File "./mailspoof", line 10, in <module>
    sys.exit(main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mailspoof/__init__.py", line 42, in main
    'issues': spoof_check(domain)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mailspoof/scanners.py", line 249, in __call__
    return self.spf_check(domain) + self.dmarc_check(domain)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mailspoof/scanners.py", line 40, in __call__
    spf_record = self.fetch(domain)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mailspoof/scanners.py", line 225, in __call__
    txt_records = self.resolver.query(domain, 'TXT')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dns/resolver.py", line 1041, in query
    timeout = self._compute_timeout(start)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dns/resolver.py", line 858, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 5.002980947494507 seconds
